swagger: '2.0'
info:
  description: API para acesso às informações de alunos de graduação da Universidade de Brasília
  version: '1.0'
  title: Aluno
  termsOfService: https://sid.redes.unb.br/terms/
  contact:
    email: heloisavargass@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost:8280
basePath: /sid/Trab1/Matricula
tags:
- name: Aluno
  description: Alunos de graduação da Universidade de Brasília
schemes:
- http
paths:
  /:
    get:
      tags:
      - Aluno
      summary: Pesquisa alunos
      description: 'Pesquisa alunos pelo parametros'
      operationId: search
      produces:
      - application/json
      parameters:
        - name: nome
          in: query
          description: Nome ou parte do nome do aluno
          required: false
          type: string
       
        - name: curso
          in: query
          description: Curso ou parte do nome do curso que o aluno faz parte
          required: false
          type: string
        - name: periodoIngresso
          in: query
          description: Ano de ingresso do aluno na universidade
          required: false
          type: string
      responses:
        200:
          description: Lista de alunos dentro dos critérios de pesquisa
          schema:
            $ref: '#/definitions/AlunoList'
  /{matricula}:
    get:
      tags:
      - Aluno
      summary: ConsultaAluno
      description:  Consulta um aluno pelo sua matrícula
      operationId: addAluno
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
      - in: path
        name: matricula
        description: Matrícula do aluno
        required: true
        type: string
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/Aluno'
        404:
          description: Não encontrado
definitions:
  periodoIngresso:
    type: object
    properties:
      ano:
        type: integer
        example: 2017
      numero:
        type: integer
        example: 2
  curso:
    type: object
    properties:
      codigo:
        type: string
        example: ERC
      nome:
        type: string
        example: ENGENHARIA DE REDES DE COMUNICAÇÃO
      turno:
        type: string
        example: Integral
      cargaHorariaTotalMinima:
        type: integer
        example: 3750
      cargaHorariaOptativalMinima:
        type: integer
        example: 1740
      numPeriodoMaximo:
        type: integer
        example: 20
      numPeriodoMinimo:
        type: integer
        example: 10
      modalidade:
        type: string
        example: Presencial
      grau:
        type: string
        example: Bacharel
  Aluno:
    type: object
    properties:
      matricula:
        type: string
        example: 170121119
      nome:
        type: string
        example: HELOISA VARGAS
      ira:
        type: number
        example: 3.8
      periodoLetivo:
        $ref: '#/definitions/periodoIngresso'
      curso:
        $ref: '#/definitions/curso'
  AlunoShort:
    type: object
    properties:
      matricula:
        type: string
        example: 170121119
      nome:
        type: string
        example: HELOISA VARGAS
  AlunoList:
    type: array
    items:
      $ref: '#/definitions/AlunoShort'