swagger: '2.0'
info:
  description: 'Servico de entidade Matricula.'
  version: 1.0.0
  title: Matricula
  termsOfService: https://sid.redes.unb.br/terms/
  contact:
    email: brunoscholles@outlook.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost:8280
basePath: /sid/Trab1/Matricula
tags:
  - name: matricula
  - name: aluno
  - name: turma
schemes:
  - http
paths:
  /:
    post:
      tags:
        - matricula
      summary: cria uma matricula
      description: 'Criacao de uma matricula para cada aluno em uma turma'
      operationId: inserir
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: matricula
          in: body
          description: Matricula praa ser criada
          required: true
          schema:
            $ref: '#/definitions/CreateMatricula'
      responses:
        '201':
          description: created
          schema:
            $ref: '#/definitions/Matricula'
        '400':
          description: bad request
        '404':
          description: not found (dados nao encontrados)
    put:
      tags:
        - matricula
      summary: atualizacao do status de uma matricula  
      description: 'Atualiza o status de uma matricula. As propriedades "aluno" e "turma" sao usadas para identificar qual a matrícula que sera atualizada. Portanto, essas propriedades dever ter valores validos e existentes. Opcionalmente, a prioridade também pode ser atualizada.'
      operationId: atualizar
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: matricula
          in: body
          description: Matricula atualizada
          required: true
          schema:
            $ref: '#/definitions/CreateMatricula'
      responses:
        '200':
          description: ok
          schema:
            $ref: '#/definitions/Matricula'
        '400':
          description: bad request
        '404':
          description: not found (dados nao encontrados)
  

  
  '/{periodoLetivo}/aluno/{aluno}/turma/{turma.disciplina}/{turma.codigo}':
    parameters:
      - name: periodoLetivo
        in: path
        description: 'Referente ao periodo letivo. EXEMPLO USADO: 2021-1'
        required: true
        type: string
      - name: aluno
        in: path
        description: 'Referente a matricula do aluno. EXEMPLO USADO: 170161668'
        required: true
        type: string
      - name: turma.disciplina
        in: path
        description: 'Referente ao codigo da disciplina da turma. EXEMPLO USADO: ENE0209'
        required: true
        type: string
      - name: turma.codigo
        in: path
        description: 'Codigo referente a turma.'
        required: true
        type: string
    get:
      tags:
        - matricula
      operationId: consultar
      produces:
        - application/json
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/Matricula'
        404:
          description: not found
    delete:
      tags: 
        - matricula
      responses:
        200:
          description: ok
        404:
          description: not found
  

  
  '/{periodoLetivo}/aluno/{aluno}':
    parameters:
      - name: periodoLetivo
        in: path
        description: 'Referente ao periodo letivo. EXEMPLO USADO: 2021-1'
        required: true
        type: string
      - name: aluno
        in: path
        description: 'Referente a matricula do aluno. EXEMPLO USADO: 170161668'
        required: true
        type: string
    get:
      tags:
        - aluno
      parameters:
        - name: status
          in: query
          required: true
          type: string
          description: Descreve o estado da matrícula ao usuario
          enum: [
                "Pre-Matricula",
                "Confirmado",
                "Retirado",
                "Pedido",
                "Cancelado",
                "Matriculado",
                "Indeferido",
                "Trancamento"
          ]
      operationId: pesquisarAluno
      produces:
        - application/json
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/MatriculasAluno'
  


  '/{periodoLetivo}/turma/{turma.disciplina}/{turma.codigo}':
    parameters:
      - name: periodoLetivo
        in: path
        description: 'Referente ao periodo letivo. EXEMPLO USADO: 2021-1'
        required: true
        type: string
      - name: turma.disciplina
        in: path
        description: 'Referente ao codigo da disciplina da turma. EXEMPLO USADO: ENE0209'
        required: true
        type: string
      - name: turma.codigo
        in: path
        description: 'Codigo referente a turma.'
        required: true
        type: string
    get:
      tags:
        - turma
      parameters:
        - name: status
          in: query
          required: true
          type: string
          description: Descreve o estado da matrícula ao usuario
          enum: [
                "Pre-Matricula",
                "Confirmado",
                "Retirado",
                "Pedido",
                "Cancelado",
                "Matriculado",
                "Indeferido",
                "Trancamento"
          ]
      operationId: pesquisarTurma
      produces:
        - application/json
      responses:
        200:
          description: ok
          schema:
            $ref: '#/definitions/MatriculasTurma'


definitions:
  CreateMatricula:
    type: object
    properties:
      aluno:
        $ref: '#/definitions/AlunoShort'
      turma:
        $ref: '#/definitions/TurmaShort'
      status:
        $ref: '#/definitions/StatusMatricula'
      prioridade:
        type: integer
        example: 1
    required: 
      - aluno
      - turma
      - status
  

  Matricula:
    type: object
    properties:
      aluno:
        $ref: '#/definitions/AlunoShort'
      turma:
        $ref: '#/definitions/TurmaShort'
      status:
        $ref: '#/definitions/StatusMatricula'
      prioridade:
        type: integer
        example: 1
    required: 
      - aluno
      - turma
      - status
  

  MatriculaAluno:
    type: object
    properties:
      turma:
        $ref: '#/definitions/TurmaShort'
      status:
        $ref: '#/definitions/StatusMatricula'
      prioridade:
        type: integer
        example: 1
    required: 
      - turma
      - status
  

  MatriculaTurma:
    type: object
    properties:
      aluno:
        $ref: '#/definitions/AlunoShort'
      status:
        $ref: '#/definitions/StatusMatricula'
      prioridade:
        type: integer
        example: 1
    required: 
      - aluno
      - turma
      - status      
  

  MatriculasTurma:
    type: array
    items:
      $ref: '#/definitions/MatriculaTurma'


  StatusMatricula:
    type: string
    description: Descreve o estado da matrícula ao usuario
    enum: [
          "Pre-Matricula",
          "Confirmado",
          "Retirado",
          "Pedido",
          "Cancelado",
          "Matriculado",
          "Indeferido",
          "Trancamento"
    ] 


  DisciplinaShort:
    type: object
    properties:
      codigo:
        type: string
        example: ENE0209
      nome:
        type: string
        example: PROCESSAMENTO DIGITAL DE IMAGENS
      cargaHorariaTotal:
        type: integer
        example: 60
      unidadeAcademica:
        type: string
        example: ENE


  TurmaShort:
        type: object
        properties:
          periodoLetivo:
            type: object
            properties:
              ano:
                type: integer
                description: Referente ao Ano Letivo
                example: 2021
              numero:
                type: integer
                description: Referente ao numero do periodo letivo
                example: 1
            required:
              - ano
              - numero
          codigo:
            type: string
            example: A
          disciplina:
            $ref: '#/definitions/DisciplinaShort'
          horariosAula:
            type: array
            items:
              type: object
              properties:
                dia:
                  type: string
                  example: SEG
                hora:
                  type: string
                  example: 16:00-17:50
        required:
          - periodoLetivo
          - codigo
          - disciplina

  
  MatriculasAluno:
    type: array
    items:
      $ref: '#/definitions/MatriculaAluno'


  AlunoShort:
        type: object
        properties:
          matricula:
            type: string
            description: Referente a matricula do aluno
            example: 170161668
          nome:
            type: string
            example: BRUNO SCHOLLES SOARES DIAS